branches:
  only:
    - master

image: Visual Studio 2015

install:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py install'

before_build:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py cmake'

build_script:
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%\build && dir'
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py build'

platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true

artifacts:
  - path: 'install\*.*'
