branches:
  only:
    - master

image: Visual Studio 2015

install:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py install'

before_build:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py cmake'

build_script:
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%\build && dir'
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows.py build'

platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true

after_build:
  - cmd: '7z a %APPVEYOR_BUILD_FOLDER%\artifact.zip %APPVEYOR_BUILD_FOLDER%\install\*'

artifacts:
  - path: install\artifact.zip

deploy:
  - provider: BinTray
    username: madeso
    api_key:
      # api key from https://bintray.com/profile/edit
      # encrypted in https://ci.appveyor.com/tools/encrypt
      secure: 4+yuIks0NBwT5o8cMeC0uc2qRFlG8y3rhyRtalbby0wwlCTBlquzVQqQSVdm2a1J
    subject: madeso
    repo: ride-generic
    package: ride-master
    version: master
    publish: true
    override: true
    explode: true
